openapi: 3.0.0
info:
  title: Google Sheet Invoice API
  description: API to retrieve invoice data from Google Sheets
  version: 1.0.0

servers:
  - url: https://google-sheets-api-xkwq.onrender.com

paths:
  /sheet-data:
    get:
      summary: Get invoice data from Google Sheets
      operationId: getSheetData
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: array
                      items:
                        type: string
